Repository pytroll/trollmoves, pull requests merged in 2020-03, with the labels that each got.

#58 Publish messages after dispatch
  bin/dispatcher.py
  examples/dispatch.yaml
  trollmoves/dispatcher.py
  trollmoves/tests/test_dispatcher.py
Labels: enhancement

#59 Fix rpm names for newer distros
  setup.cfg
Labels: enhancement

#57 Reload only the actual config file when it is modified
  bin/move_it.py
Labels: bug, enhancement

#60 Fix iterate_messages() generator raising StopIteration
  trollmoves/client.py
  trollmoves/tests/test_client.py
Labels: bug
